dist: xenial
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 12
  - 10
  - 13
stages:
  - lint
addons:
  chrome: stable
jobs:
  include:
    - stage: lint
      install: npm run setup
      script:
        - npm run lint