language: node_js
stages:
  - lint
  - unit
addons:
  chrome: stable
jobs:
  include:
    - stage: lint
      node_js: 13
      install: 
        - cd js-backend
        - npm install
      script:
        - npm run lint
    - stage: lint
      node_js: 13
      install: 
        - cd vue-ui
        - npm install
      script:
        - npm run lint
    - stage: unit
      node_js: 13
      install: 
        - cd vue-ui
        - npm install
      script:
        - npm run test:unit
    - stage: unit
      node_js: 13
      install: 
        - cd js-backend
        - npm install
      script:
        - npm run test:unit