language: node_js
node_js: 13
stages:
  #- lint
  #- unit
  - e2e
services:
  - docker
#addons:
#  chrome: stable
jobs:
  include:
    - stage: lint
      install: 
        - cd js-backend
        - npm install
      script:
        - npm run lint
    - stage: lint
      install: 
        - cd vue-ui
        - npm install
      script:
        - npm run lint
    - stage: unit
      install: 
        - cd vue-ui
        - npm install
      script:
        - npm run test:unit
    - stage: unit
      install: 
        - cd js-backend
        - npm install
      script:
        - npm run test:unit
    - stage: e2e
      script:
        - chmod -R 775 .
        - source ./.env
        - docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.cypress.yml up --build --exit-code-from e2e