dist: xenial
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 12
  - 10
  - 13
stages:
  - lint
jobs:
  include:
    - stage: lint
      script:
        - cd js-backend && npm install && npm run lint && cd ..
        - cd vue-ui && npm install && npm run lint && cd ..